### ISSUE TITLE
turning parsed QueryDict values to list

### ISSUE THREAD

**Issue by badmoham** [remigermain/nested-multipart-parser#10]
**Describe the bug**
while using it in DRF, it will return QueryDict with values type of list only , it will append all values to an extra list and return it with an extra layer of list.

**To Reproduce**
for example:
here is the multipart/FormDate sent by client in browser using react native:
    ticket_detail[0][description]: some lorem ipsum
    title: current subject
    department: general-department
and here is the parsed QueryDict :
    <QueryDict: {'ticket_detail': [[{'description': 'some lorem ipsum'}]], 'title': ['current subject'], 'department': ['general-department']}>

as you can see it parse the "title: current subject" to "'title': ['current subject']" with value type of a list, which was expected to be str.

**Screenshots**
![image](https://github.com/remigermain/nested-multipart-parser/assets/37850275/c2b06f3d-2c03-4ef2-9267-c9bfacfb1202)
![image](https://github.com/remigermain/nested-multipart-parser/assets/37850275/a6746eb1-0956-4af9-a940-d73dffededbe)

and thank you for your great work!

**Comment by remigermain** [comment]
Hey, you have a options to not convert it to querydict, in settings.py :
 ``DRF_NESTED_MULTIPART_PARSER = { 	"querydict": False }``

**Comment by remigermain** [comment]
Hey, you have a options to not convert it to querydict, in settings.py :
 ``DRF_NESTED_MULTIPART_PARSER = { 	"querydict": False }``

Related #7

**Comment by badmoham** [comment]
thank you very much for your response

**Comment by csirmazbendeguz** [comment]
Hi @remigermain , I just ran into the same issue. Thanks!

I wonder why convert to QueryDict in the first place? I think it would be better to either disable this conversion by default or remove it altogether

**Comment by remigermain** [comment]
Hey @csirmazbendeguz ,  according to the Django docs, it was preferable to do this since everything were "queryparams", so I judged that it was good to convert everything to QueryDict. With time and experience, options shouldn't exist and should return directly a dict (especially since the parser doesn't accept multiple values for the same key). Bad analysis and not enough experience to have realized it 😄 

Currently, I couldn't default it to true, a big compatibility change, but tagging a new version at 2.0.0, why not.
